=== ZacharyGeurts/AmmoOS/GIMP-Field/tree/authors.dtd
<!-- simple DTD for AmmoOS Image authors -->

<!ELEMENT ammoos-authors (creator+, maintainer+, contributor+)>
<!ATTLIST ammoos-authors xmlns CDATA #FIXED "http://purl.org/dc/elements/1.1/">

<!ELEMENT creator (#PCDATA)>
<!ATTLIST creator role CDATA #REQUIRED>
<!ATTLIST creator last-active CDATA #REQUIRED>

<!ELEMENT maintainer (#PCDATA)>
<!ATTLIST maintainer role CDATA #REQUIRED>
<!ATTLIST maintainer last-active CDATA #REQUIRED>

<!ELEMENT contributor (#PCDATA)>
<!ATTLIST contributor role CDATA #REQUIRED>
<!ATTLIST contributor last-active CDATA #REQUIRED>

=== ZacharyGeurts/AmmoOS/GIMP-Field/tree/authors.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ammoos-authors SYSTEM "authors.dtd">

<!-- This file is supposed to list all AmmoOS Image authors and contributors.       -->
<!-- It's in XML format so that it can easily be used for the About dialog. -->

<!-- When changing this file, please keep the alphabetical order.           -->

<ammoos-authors xmlns="http://purl.org/dc/elements/1.1/">

  <creator role="author" last-active="2.2">Spencer Kimball</creator>
  <creator role="author" last-active="1.0">Peter Mattis</creator>

  <maintainer role="author" last-active="3.2">Michael Natterer</maintainer>
  <maintainer role="author" last-active="3.2">Jehan</maintainer>

  <contributor role="author" last-active="1.2">Lauri Alanko</contributor>
  <contributor role="author" last-active="2.8">Fredrik Alströmer</contributor>
  <contributor role="author" last-active="1.2">Shawn Amundson</contributor>
  <contributor role="author" last-active="1.2">Sven Anders</contributor>
  <contributor role="author" last-active="3.0">Luca Bacci</contributor>
  <contributor role="author" last-active="2.4">Henrik Brix Andersen</contributor>
  <contributor role="author" last-active="1.0">Karl-Johan Andersson</contributor>
  <contributor role="documenter" last-active="2.6">Ignacio AntI</contributor>
  <contributor role="author" last-active="2.8">Rob Antonishen</contributor>
  <contributor role="author" last-active="2.6">Nicola Archibald</contributor>
  <contributor role="author" last-active="2.10">Timm Bäder</contributor>
  <contributor role="author" last-active="3.2">Gabriele Barbero</contributor>
  <contributor role="author" last-active="2.6">Luis Barrancos</contributor>
  <contributor role="author" last-active="2.8">Jerry Baker</contributor>
  <contributor role="author" last-active="1.0">John Beale</contributor>
  <contributor role="author" last-active="2.0">Zach Beane</contributor>
  <contributor role="author" last-active="1.0">Tom Bech</contributor>
  <contributor role="documenter" last-active="2.6">Žygimantas Beručka</contributor>
  <contributor role="author" last-active="2.10">Daniel P. Berrange</contributor>
  <contributor role="author" last-active="1.0">Marc Bless</contributor>
  <contributor role="author" last-active="1.0">Edward Blevins</contributor>
  <contributor role="author" last-active="1.0">Reagan Blundell</contributor>
  <contributor role="author documenter" last-active="3.2">Jacob Boerema</contributor>
  <contributor role="author" last-active="2.8">Hendrik Boom</contributor>
  <contributor role="author" last-active="1.0">Xavier Bouchoux</contributor>
  <contributor role="author" last-active="2.8">Richard Bowers</contributor>
  <contributor role="author" last-active="1.2">Roberto Boyd</contributor>
  <contributor role="author" last-active="2.0">Stanislav Brabec</contributor>
  <contributor role="author" last-active="2.8">Hans Breuer</contributor>
  <contributor role="author" last-active="3.0">Simon Budig</contributor>
  <contributor role="author" last-active="2.10">João S. O. Bueno</contributor>
  <contributor role="documenter" last-active="1.2">Carey Bunks</contributor>
  <contributor role="author" last-active="2.8">Seth Burgess</contributor>
  <contributor role="author" last-active="1.0">Brent Burton</contributor>
  <contributor role="author" last-active="1.0">Francisco Bustamante</contributor>
  <contributor role="author" last-active="1.0">Albert Cahalan</contributor>
  <contributor role="artist" last-active="2.4">Lapo Calamandrei</contributor>
  <contributor role="author" last-active="2.0">George J. Carrette</contributor>
  <contributor role="author documenter" last-active="2.8">Marco Ciampa</contributor>
  <contributor role="author" last-active="1.0">Sean Cier</contributor>
  <contributor role="author" last-active="2.8">Winston Chang</contributor>
  <contributor role="author" last-active="2.4">Stephane Chauveau</contributor>
  <contributor role="author" last-active="2.4">Zbigniew Chyla</contributor>
  <contributor role="author" last-active="2.8">Lars-Peter Clausen</contributor>
  <contributor role="author documenter" last-active="2.8">Sven Claussner</contributor>
  <contributor role="author" last-active="2.0">Branko Collin</contributor>
  <contributor role="author" last-active="1.0">Ed Connel</contributor>
  <contributor role="author" last-active="1.2">Piers Cornwell</contributor>
  <contributor role="author" last-active="2.4">David Costanzo</contributor>
  <contributor role="author" last-active="1.0">Daniel Cotting</contributor>
  <contributor role="author" last-active="2.4">Jay Cox</contributor>
  <contributor role="author" last-active="2.10">Kevin Cozens</contributor>
  <contributor role="author" last-active="2.10">Jeremiah Darais</contributor>
  <contributor role="author" last-active="3.0">Shubham Daule</contributor>
  <contributor role="artist" last-active="2.4">Paul Davey</contributor>
  <contributor role="artist documenter" last-active="3.0">Patrick David</contributor>
  <contributor role="author" last-active="2.6">Michael Deal</contributor>
  <contributor role="artist author" last-active="2.10">Alexia Death</contributor>
  <contributor role="author" last-active="1.0">Brian Degenhardt</contributor>
  <contributor role="author" last-active="2.4">Karine Delvare</contributor>
  <contributor role="artist" last-active="2.6">Aurore Derriennic</contributor>
  <contributor role="author" last-active="1.0">Andreas Dilger</contributor>
  <contributor role="author" last-active="2.8">Nicholas Doyle</contributor>
  <contributor role="author" last-active="2.0">Austin Donnelly</contributor>
  <contributor role="author" last-active="1.0">Scott Draves</contributor>
  <contributor role="author" last-active="1.0">Daniel Dunbar</contributor>
  <contributor role="documenter" last-active="2.6">Dust</contributor>
  <contributor role="author" last-active="2.10">Marek Dvoroznak</contributor>
  <contributor role="author" last-active="1.2">Misha Dynin</contributor>
  <contributor role="author" last-active="2.8">Daniel Eddeland</contributor>
  <contributor role="author" last-active="2.4">Daniel Egger</contributor>
  <contributor role="author documenter" last-active="2.8">Ulf-D. Ehlert</contributor>
  <contributor role="author" last-active="2.10">Gil Eliyahu</contributor>
  <contributor role="author" last-active="3.0">Tobias Ellinghaus</contributor>
  <contributor role="author" last-active="3.0">Ell</contributor>
  <contributor role="author" last-active="2.0">Morton Eriksen</contributor>
  <contributor role="author" last-active="2.0">Larry Ewing</contributor>
  <contributor role="documenter" last-active="2.6">Alessandro Falappa</contributor>
  <contributor role="author" last-active="2.10">Dirk Farin</contributor>
  <contributor role="author" last-active="3.2">Idriss Fekir</contributor>
  <contributor role="author" last-active="2.4">Pedro Alonso Ferrer</contributor>
  <contributor role="author" last-active="1.2">Nick Fetchak</contributor>
  <contributor role="author" last-active="2.4">Piotr Filiciak</contributor>
  <contributor role="author" last-active="2.4">Shlomi Fish</contributor>
  <contributor role="author" last-active="2.4">Sylvain Foret</contributor>
  <contributor role="author" last-active="1.0">David Forsyth</contributor>
  <contributor role="author" last-active="1.0">Raphael Francois</contributor>
  <contributor role="documenter" last-active="2.4">Jakub Friedl</contributor>
  <contributor role="author" last-active="2.4">Gerald Friedland</contributor>
  <contributor role="author" last-active="1.0">Jochen Friedrich</contributor>
  <contributor role="author" last-active="2.4">Daniel Richard G</contributor>
  <contributor role="author" last-active="2.2">Jordi Gay</contributor>
  <contributor role="author" last-active="1.2">Jim Geuther</contributor>
  <contributor role="author" last-active="2.4">GG</contributor>
  <contributor role="author" last-active="3.0">Carlos Garnacho</contributor>
  <contributor role="author" last-active="2.0">Graeme Gill</contributor>
  <contributor role="author" last-active="2.2">Pedro Gimeno</contributor>
  <contributor role="author" last-active="2.10">Richard Gitschlag</contributor>
  <contributor role="author" last-active="1.2">Scott Goehring</contributor>
  <contributor role="author" last-active="1.2">Heiko Goller</contributor>
  <contributor role="author" last-active="1.0">Marcelo de Gomensoro Malheiros</contributor>
  <contributor role="author" last-active="2.10">Saul Goode</contributor>
  <contributor role="author" last-active="2.8">David Gowers</contributor>
  <contributor role="author documenter" last-active="3.2">Niels De Graef</contributor>
  <contributor role="author" last-active="2.10">Cameron Gregory</contributor>
  <contributor role="author" last-active="3.0">Stanislav Grinkov</contributor>
  <contributor role="author" last-active="2.8">Eric Grivel</contributor>
  <contributor role="author" last-active="2.8">Stephen Griffiths</contributor>
  <contributor role="author" last-active="1.2">Pavel Grinfeld</contributor>
  <contributor role="author" last-active="2.4">Dov Grobgeld</contributor>
  <contributor role="artist" last-active="2.10">Philipp Haegi</contributor>
  <contributor role="author documenter" last-active="2.4">Michael Hammel</contributor>
  <contributor role="author documenter" last-active="2.10">Julien Hardelin</contributor>
  <contributor role="artist" last-active="3.2">Aryeom Han</contributor>
  <contributor role="author" last-active="2.8">Tim Harder</contributor>
  <contributor role="author" last-active="2.6">Marcus Heese</contributor>
  <contributor role="author" last-active="2.4">Robert Helgesson</contributor>
  <contributor role="author" last-active="2.10">Michael Henning</contributor>
  <contributor role="author" last-active="2.0">James Henstridge</contributor>
  <contributor role="author" last-active="1.0">Eric Hernes</contributor>
  <contributor role="author" last-active="2.8">Lukasz Hladowski</contributor>
